name: Automate deployment

on:
  push:
    branches:
      main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: corretto

      - name: build with maven
        run: mvn clean install

      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: target/elastic-beanstalk-java-0.0.1-SNAPSHOT.jar

  deployment:
    needs: build
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Beanstalk Deploy for JAR
        uses: DylanBDev/beanstalk-deploy@initial
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: elastic-beanstalk-java
          environment_name: Elastic-beanstalk-java-env
          version_label: $ {{ github.SHA }}
          region: us-central-1
          deployment_package: elastic-beanstalk-java-0.0.1-SNAPSHOT.jar